// Generated by gencpp from file serial_comm/Ticks.msg
// DO NOT EDIT!


#ifndef SERIAL_COMM_MESSAGE_TICKS_H
#define SERIAL_COMM_MESSAGE_TICKS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serial_comm
{
template <class ContainerAllocator>
struct Ticks_
{
  typedef Ticks_<ContainerAllocator> Type;

  Ticks_()
    : left(0)
    , right(0)  {
    }
  Ticks_(const ContainerAllocator& _alloc)
    : left(0)
    , right(0)  {
  (void)_alloc;
    }



   typedef int16_t _left_type;
  _left_type left;

   typedef int16_t _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::serial_comm::Ticks_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_comm::Ticks_<ContainerAllocator> const> ConstPtr;

}; // struct Ticks_

typedef ::serial_comm::Ticks_<std::allocator<void> > Ticks;

typedef boost::shared_ptr< ::serial_comm::Ticks > TicksPtr;
typedef boost::shared_ptr< ::serial_comm::Ticks const> TicksConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_comm::Ticks_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_comm::Ticks_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::serial_comm::Ticks_<ContainerAllocator1> & lhs, const ::serial_comm::Ticks_<ContainerAllocator2> & rhs)
{
  return lhs.left == rhs.left &&
    lhs.right == rhs.right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::serial_comm::Ticks_<ContainerAllocator1> & lhs, const ::serial_comm::Ticks_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace serial_comm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::serial_comm::Ticks_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_comm::Ticks_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_comm::Ticks_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_comm::Ticks_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_comm::Ticks_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_comm::Ticks_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_comm::Ticks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "09d1b2323a1aeae9343e81809a820b60";
  }

  static const char* value(const ::serial_comm::Ticks_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x09d1b2323a1aeae9ULL;
  static const uint64_t static_value2 = 0x343e81809a820b60ULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_comm::Ticks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_comm/Ticks";
  }

  static const char* value(const ::serial_comm::Ticks_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_comm::Ticks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 left\n"
"int16 right\n"
;
  }

  static const char* value(const ::serial_comm::Ticks_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_comm::Ticks_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ticks_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_comm::Ticks_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_comm::Ticks_<ContainerAllocator>& v)
  {
    s << indent << "left: ";
    Printer<int16_t>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<int16_t>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_COMM_MESSAGE_TICKS_H
